name: airsoft_app
description: Airsoft app foundation for Android and iOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
