-- 011_seed_shops_and_fields.sql
-- Updated seed data using real Japan airsoft shops/fields requested by user.
-- Idempotent: dedupes by case-insensitive name.

insert into public.shops (
  name,
  address,
  prefecture,
  city,
  opening_times,
  phone_number,
  features,
  image_url,
  latitude,
  longitude,
  is_official
)
select
  seed.name,
  seed.address,
  seed.prefecture,
  seed.city,
  seed.opening_times,
  seed.phone_number,
  seed.features,
  seed.image_url,
  seed.latitude,
  seed.longitude,
  seed.is_official
from (
  values
    (
      'ECHIGOYA Akihabara',
      'Sotokanda, Chiyoda-ku, Tokyo',
      'Tokyo',
      'Chiyoda',
      'Weekdays 11:00-21:00, Sun/Holidays 11:00-20:00',
      '+81-3-5289-7009',
      'Major Tokyo airsoft retailer, wide gun and parts selection, long-established store',
      null,
      35.7024,
      139.7712,
      true
    ),
    (
      'ECHIGOYA Shinjuku',
      'Shinjuku, Tokyo',
      'Tokyo',
      'Shinjuku',
      'Weekdays 11:00-21:00, Sun/Holidays 11:00-20:00',
      null,
      'Major Tokyo airsoft retailer, central Tokyo branch',
      null,
      null,
      null,
      true
    ),
    (
      '41PX',
      'Sotokanda 5-1-3, Chiyoda-ku, Tokyo',
      'Tokyo',
      'Chiyoda',
      'Unknown',
      '+81-70-6420-6523',
      'Popular tactical and airsoft shop, strong accessories and gear range',
      null,
      null,
      null,
      true
    ),
    (
      'MIL-FREAKS',
      '4-7-5 Sotokanda Ishikawa Kosan Building 2F, Chiyoda-ku, Tokyo',
      'Tokyo',
      'Chiyoda',
      '11:00-21:00',
      null,
      'Military gear and apparel, strong equipment selection, Akihabara location',
      null,
      null,
      null,
      true
    ),
    (
      'Rep-Mart',
      'Tokyo',
      'Tokyo',
      'Tokyo',
      'Unknown',
      null,
      'Military and survival gear retailer',
      null,
      null,
      null,
      false
    ),
    (
      'Mokei Paddock',
      'Chiba',
      'Chiba',
      'Yotsukaido',
      'Unknown',
      null,
      'Large airsoft shop, custom work, repair, range and field facilities',
      null,
      null,
      null,
      true
    )
) as seed(
  name,
  address,
  prefecture,
  city,
  opening_times,
  phone_number,
  features,
  image_url,
  latitude,
  longitude,
  is_official
)
where not exists (
  select 1
  from public.shops s
  where lower(s.name) = lower(seed.name)
);

insert into public.fields (
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
select
  seed.name,
  seed.location_name,
  seed.prefecture,
  seed.city,
  seed.latitude,
  seed.longitude,
  seed.field_type,
  seed.description,
  seed.feature_list,
  seed.pros_list,
  seed.cons_list,
  seed.phone,
  seed.email,
  seed.website,
  seed.instagram,
  seed.facebook,
  seed.x,
  seed.youtube,
  seed.image_url
from (
  values
    (
      'No.9',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large survival game field in Inzai with multiple field areas and strong rental support.',
      'Multiple field layouts, rentals, BBQ, safe area, large capacity',
      'Very established, beginner friendly, large-scale events',
      'Busy on popular event days',
      null,
      null,
      'https://www.no9-co.jp/',
      null,
      null,
      '@No9SURVIVALGAME',
      null,
      null
    ),
    (
      'Battle',
      'Chiba',
      'Chiba',
      'Chiba',
      null,
      null,
      'Outdoor',
      'Large-scale urban-style survival game field.',
      'Urban combat style, rental support',
      'Good for objective games',
      'Exact metadata pending',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'BEAM',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large Chiba field with spacious safe zone, long shooting range and several field areas.',
      'Large safe area, shooting range, rentals, parking, BBQ',
      'Popular and accessible, large parking capacity',
      'Weekends can be crowded',
      null,
      null,
      'https://beam-sg.com/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Ikusa',
      'Unknown',
      'Chiba',
      'Unknown',
      null,
      null,
      'Outdoor',
      'Airsoft field entry requested by user.',
      'Field info pending',
      'Requested by user',
      'Metadata not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Sengoku',
      'Unknown',
      'Chiba',
      'Unknown',
      null,
      null,
      'Outdoor',
      'Airsoft field entry requested by user.',
      'Field info pending',
      'Requested by user',
      'Metadata not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Battle Union',
      'Chiba',
      'Chiba',
      'Chiba',
      null,
      null,
      'Outdoor',
      'Urban-style large-scale survival game field under the Battle Union branding.',
      'Large city-style map, rental support',
      'Well-known field group',
      'Specific sub-field metadata may vary',
      null,
      null,
      'https://www.battle-union.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Union Base',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Well-known Chiba field in the Union group with large outdoor play areas.',
      'Large outdoor field, event support',
      'Established field network',
      'Detailed metadata not added here',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'CIMAX',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large outdoor field and activity site in Chiba used for survival games and other outdoor activities.',
      'Large field, rentals, access support, outdoor facilities',
      'Popular Kanto destination',
      'Mixed-use site',
      null,
      null,
      'https://www.cimax.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Desert Union',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large desert-themed survival game field in Chiba.',
      'Open terrain, large map, regular games',
      'Distinct terrain style',
      'Less cover than forest-focused fields',
      '090-8740-3394',
      null,
      'https://desert-union.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Forest Union',
      'Inzai',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large forest-themed survival game field in Chiba.',
      'Forest terrain, regular games, large map',
      'Strong woodland gameplay',
      'Less suited to pure CQB players',
      '090-6030-5588',
      null,
      'https://forest-union.jp/',
      null,
      null,
      null,
      null,
      null
    )
) as seed(
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
where not exists (
  select 1
  from public.fields f
  where lower(f.name) = lower(seed.name)
);