insert into public.fields (
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
select
  seed.name,
  seed.location_name,
  seed.prefecture,
  seed.city,
  seed.latitude,
  seed.longitude,
  seed.field_type,
  seed.description,
  seed.feature_list,
  seed.pros_list,
  seed.cons_list,
  seed.phone,
  seed.email,
  seed.website,
  seed.instagram,
  seed.facebook,
  seed.x,
  seed.youtube,
  seed.image_url
from (
  values
    (
      'No.9',
      'Iwato',
      'Chiba',
      'Inzai',
      35.7629375,
      140.1657961,
      'Outdoor',
      'Large outdoor survival game field in Inzai with multiple field zones and strong beginner support.',
      'Multiple fields, rentals, BBQ, shooting range, large capacity',
      'Very established, strong regular events, good for large groups',
      'Can be busy on event days',
      '0476-99-0910',
      null,
      'https://www.no9-co.jp/',
      'https://www.instagram.com/survival_game_no9/',
      'https://www.facebook.com/survivalNo9',
      'https://x.com/No9SURVIVALGAME',
      null,
      null
    ),
    (
      'Battle City',
      'Kamibessho',
      'Chiba',
      'Sakura',
      null,
      null,
      'Mixed',
      'Large city-style survival game field with urban and woodland elements.',
      'Urban combat areas, woodland sections, regular games',
      'Iconic urban-style field, good for objective play',
      'Exact coordinates still pending',
      '080-1204-8849',
      null,
      'https://www.battle-union.jp/',
      'https://www.instagram.com/battlecity_survivalgamefield/',
      null,
      null,
      null,
      null
    ),
    (
      'BEAM',
      'Hiraka',
      'Chiba',
      'Inzai',
      35.75689,
      140.252142,
      'Outdoor',
      'Large outdoor field in Inzai with multiple distinct play zones.',
      '5 field types, rentals, parking, BBQ, shooting range',
      'Popular, varied layouts, strong beginner access',
      'Crowded on peak days',
      '090-2736-1100',
      null,
      'https://beam-sg.com/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Ikusa',
      'Unknown',
      'Unknown',
      'Unknown',
      null,
      null,
      'Unknown',
      'Field requested by user. Exact official field data still pending verification.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Sengoku',
      'Unknown',
      'Unknown',
      'Unknown',
      null,
      null,
      'Unknown',
      'Field requested by user. Exact official field data still pending verification.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Battle Union',
      'Unknown',
      'Chiba',
      'Unknown',
      null,
      null,
      'Outdoor',
      'Battle Union brand field entry requested by user.',
      'Metadata pending',
      'Requested by user',
      'May refer to Battle City / related Union network field',
      null,
      null,
      'https://www.battle-union.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Union Base',
      'Hiraka',
      'Chiba',
      'Inzai',
      null,
      null,
      'Mixed',
      'Well-known Union group field with buildings and elevation mixed into outdoor play.',
      'Buildings, outdoor terrain, BBQ, event support',
      'Established field, good scenario variety',
      'Exact coordinates still pending',
      '0476-76-9617',
      null,
      'https://union-base.com/',
      null,
      'https://www.facebook.com/unionbasesgf/',
      null,
      null,
      null
    ),
    (
      'CIMAX',
      'Moroto',
      'Chiba',
      'Inzai',
      35.7670256,
      140.1848615,
      'Outdoor',
      'Large outdoor activity field used for survival games and other outdoor activities.',
      'Large field, rentals, buggy activities, family-friendly facilities',
      'Big site, established destination',
      'Mixed-use site may not suit all styles',
      '0476-99-3510',
      null,
      'https://www.cimax.jp/',
      null,
      null,
      'https://twitter.com/cimaxmax',
      null,
      null
    ),
    (
      'Desert Union',
      'Hiraka',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large desert-themed survival game field in Inzai.',
      'Open terrain, large map, regular events',
      'Distinct terrain style, strong for long-range engagements',
      'Less cover than woodland-focused fields',
      '090-8740-3394',
      null,
      'https://desert-union.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Forest Union',
      'Hiraka',
      'Chiba',
      'Inzai',
      null,
      null,
      'Outdoor',
      'Large forest-themed survival game field in Inzai.',
      'Forest terrain, large map, regular games',
      'Strong woodland gameplay',
      'Less suited to pure CQB players',
      '090-6030-5588',
      null,
      'https://forest-union.jp/',
      'https://www.instagram.com/forestunion/',
      null,
      null,
      null,
      null
    ),
    (
      'Headshot',
      'Hiraka',
      'Chiba',
      'Inzai',
      35.765436,
      140.249818,
      'Mixed',
      'Popular Inzai field with strong CQB emphasis and rental support.',
      'CQB-oriented layout, rentals, regular games',
      'Good tempo, popular field',
      'Can be punishing for newer players depending on mode',
      '080-4813-1538',
      null,
      'https://head-shot.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Tokyo Sabage Park',
      'Sofuke',
      'Chiba',
      'Inzai',
      35.790691,
      140.150265,
      'Mixed',
      'Large-scale mixed field complex in Inzai with strong event capacity.',
      'Large site, rentals, parking, regular games',
      'Good scale, reliable choice',
      'Can be busy and popular',
      '0476-48-5215',
      null,
      'https://www.tokyosabagepark.jp/',
      null,
      'https://www.facebook.com/tokyosabagepark/',
      'https://twitter.com/tokyosabagepark',
      null,
      null
    ),
    (
      'PARADOX',
      'Owashishinden',
      'Chiba',
      'Kimitsu',
      35.3288,
      139.9650,
      'Outdoor',
      'Large-scale outdoor survival game field in Kimitsu.',
      'Large forest field, rentals, regular games',
      'Good backup variety for AOJ',
      'Further from core AOJ Chiba rotation',
      '0439-29-6433',
      null,
      'https://paradoxjp.com/',
      null,
      'https://www.facebook.com/paradox.svgfield/',
      null,
      null,
      null
    ),
    (
      'U-BOX',
      'Hiraka',
      'Chiba',
      'Inzai',
      null,
      null,
      'Indoor',
      'Indoor survival game field in Inzai, useful for weather-proof CQB sessions.',
      'Indoor field, night use, rentals',
      'Good for CQB training and bad weather',
      'Exact coordinates still pending',
      '090-9815-3838',
      null,
      'https://u-box.space/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'ASOBIBA',
      'Tokyo',
      'Tokyo',
      'Tokyo',
      null,
      null,
      'Indoor',
      'Indoor survival game brand with multiple Tokyo locations.',
      'Indoor CQB, rentals, beginner-friendly',
      'Easy access, good training option',
      'Use branch-specific records later',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Brave Point Shinjuku',
      'Kabukicho',
      'Tokyo',
      'Shinjuku',
      null,
      null,
      'Indoor',
      'Indoor CQB studio in central Shinjuku.',
      'Indoor, rentals, central location',
      'Good beginner and training site',
      'Exact coordinates not added in this pass',
      '03-6265-9428',
      null,
      'https://shinjuku.brave-point.jp/',
      null,
      null,
      null,
      null,
      null
    ),
    (
      'YaNex',
      'Kanagawa',
      'Kanagawa',
      'Unknown',
      null,
      null,
      'Outdoor',
      'Outdoor field entry requested by user.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Battlefield Asaka',
      'Asaka',
      'Saitama',
      'Asaka',
      null,
      null,
      'Outdoor',
      'Field entry requested by user.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'Area41',
      'Saitama',
      'Saitama',
      'Unknown',
      null,
      null,
      'Outdoor',
      'Field entry requested by user.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ),
    (
      'ZEEK',
      'Saitama',
      'Saitama',
      'Unknown',
      null,
      null,
      'Unknown',
      'Field entry requested by user.',
      'Metadata pending',
      'Requested by user',
      'Address and coordinates not yet confirmed',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    )
) as seed(
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
where not exists (
  select 1
  from public.fields f
  where lower(f.name) = lower(seed.name)
);