-- 011_seed_shops_and_fields.sql
-- Idempotent seed data for initial Japan directory content.
-- Safe to run multiple times (dedupes by case-insensitive name).

insert into public.shops (
  name,
  address,
  prefecture,
  city,
  opening_times,
  phone_number,
  features,
  image_url,
  latitude,
  longitude,
  is_official
)
select
  seed.name,
  seed.address,
  seed.prefecture,
  seed.city,
  seed.opening_times,
  seed.phone_number,
  seed.features,
  seed.image_url,
  seed.latitude,
  seed.longitude,
  seed.is_official
from (
  values
    (
      'ECHIGOYA Akihabara',
      'Sotokanda 3-8-9, Chiyoda-ku, Tokyo',
      'Tokyo',
      'Chiyoda',
      'Mon-Sun 11:00-20:00',
      '+81-3-3257-8088',
      'Large AEG wall, GBB pistols, optics, parts, English-friendly staff',
      null,
      35.7024,
      139.7712,
      true
    ),
    (
      'FIRST Tokyo Arms',
      'Shibuya 2-22-3, Shibuya-ku, Tokyo',
      'Tokyo',
      'Shibuya',
      'Mon-Sat 12:00-20:00, Sun 12:00-19:00',
      '+81-3-1234-5678',
      'Tech bench, custom tuning, MOSFET installs, HPA fitting',
      null,
      35.6591,
      139.7037,
      false
    ),
    (
      'LayLax Osaka Store',
      'Nipponbashi 4-7-19, Naniwa-ku, Osaka',
      'Osaka',
      'Naniwa',
      'Tue-Sun 11:00-20:00',
      '+81-6-6648-5550',
      'LayLax parts, tactical gear, repair desk, chrono station',
      null,
      34.6561,
      135.5050,
      true
    ),
    (
      'GUN SHOP SYSTEM',
      'Tenjin 3-6-12, Chuo-ku, Fukuoka',
      'Fukuoka',
      'Fukuoka',
      'Mon-Sat 11:00-20:00, Sun 11:00-18:00',
      '+81-92-555-1048',
      'CQB-focused inventory, magazines, batteries, gas refills',
      null,
      33.5905,
      130.4017,
      false
    ),
    (
      'SAPPORO Survival Shop North',
      'Kita 24-jo Nishi 5-1-10, Kita-ku, Sapporo',
      'Hokkaido',
      'Sapporo',
      'Wed-Mon 12:00-19:00',
      '+81-11-600-2424',
      'Cold-weather setup advice, winter gas solutions, optics',
      null,
      43.0909,
      141.3469,
      false
    ),
    (
      'Nagoya Tactical Outlet',
      'Osu 3-20-14, Naka-ku, Nagoya',
      'Aichi',
      'Nagoya',
      'Mon-Sun 11:00-20:00',
      '+81-52-211-0921',
      'Outlet pricing, beginner starter kits, rental recommendations',
      null,
      35.1595,
      136.9066,
      false
    ),
    (
      'Yokohama Airsoft Garage',
      'Motomachi 1-42, Naka-ku, Yokohama',
      'Kanagawa',
      'Yokohama',
      'Tue-Sun 12:00-20:00',
      '+81-45-681-4011',
      'Internal upgrades, LiPo safety products, slings and plate carriers',
      null,
      35.4435,
      139.6490,
      false
    ),
    (
      'Okinawa Ranger Pro Shop',
      'Mihama 2-2-1, Chatan-cho, Nakagami-gun, Okinawa',
      'Okinawa',
      'Chatan',
      'Mon-Sun 10:00-19:00',
      '+81-98-936-8850',
      'Outdoor field supplies, hydration gear, helmets, gloves',
      null,
      26.3188,
      127.7578,
      false
    )
) as seed(
  name,
  address,
  prefecture,
  city,
  opening_times,
  phone_number,
  features,
  image_url,
  latitude,
  longitude,
  is_official
)
where not exists (
  select 1
  from public.shops s
  where lower(s.name) = lower(seed.name)
);

insert into public.fields (
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
select
  seed.name,
  seed.location_name,
  seed.prefecture,
  seed.city,
  seed.latitude,
  seed.longitude,
  seed.field_type,
  seed.description,
  seed.feature_list,
  seed.pros_list,
  seed.cons_list,
  seed.phone,
  seed.email,
  seed.website,
  seed.instagram,
  seed.facebook,
  seed.x,
  seed.youtube,
  seed.image_url
from (
  values
    (
      'RAID Chiba North',
      'Noda',
      'Chiba',
      'Noda',
      35.9632,
      139.8689,
      'Outdoor',
      'Woodland-style field with mixed cover and objective-based game modes.',
      'Safe zone, Rental AEGs, Chrono station, Parking, Shop counter',
      'Good map flow, beginner friendly staff, clear safety briefings',
      'Busy on weekends, lunch queue can get long',
      '+81-4-7190-1201',
      'info@raidchibanorth.jp',
      'https://example.com/raid-chiba-north',
      '@raidchibanorth',
      'RAID Chiba North',
      '@raidchibanorth',
      'RAID Chiba North Channel',
      null
    ),
    (
      'CQB Matrix Tokyo',
      'Adachi',
      'Tokyo',
      'Adachi',
      35.7788,
      139.7802,
      'CQB',
      'Indoor CQB arena with modular barricade layout and night games.',
      'Indoor arena, Rental masks, Tracer-friendly lighting, Pro shop',
      'Great for small teams, weather proof, close to station',
      'Can feel cramped for large groups',
      '+81-3-6802-4412',
      'hello@cqbmatrix.tokyo',
      'https://example.com/cqb-matrix-tokyo',
      '@cqbmatrixtokyo',
      'CQB Matrix Tokyo',
      '@cqbmatrixtokyo',
      'CQB Matrix Tokyo',
      null
    ),
    (
      'Kawasaki Frontline Field',
      'Kawasaki',
      'Kanagawa',
      'Kawasaki',
      35.5308,
      139.7031,
      'Mixed',
      'Mixed indoor and outdoor zones suitable for all-year play.',
      'Mixed map, Rental kit, On-site tech, Rest area, Vending',
      'Good transport links, balanced map design',
      'Limited parking spots',
      '+81-44-200-7730',
      'contact@frontline-kawasaki.jp',
      'https://example.com/frontline-kawasaki',
      '@frontlinekawasaki',
      'Kawasaki Frontline Field',
      '@frontlinekawasaki',
      'Kawasaki Frontline',
      null
    ),
    (
      'Osaka Industrial Zone',
      'Sakai',
      'Osaka',
      'Sakai',
      34.5732,
      135.4828,
      'CQB',
      'Industrial-themed CQB map with rotating objective scenarios.',
      'CQB lanes, Smoke grenades allowed, Rental packs, Night sessions',
      'High-intensity rounds, tactical map variety',
      'Not ideal for very young players',
      '+81-72-222-3800',
      'play@osaka-industrial.jp',
      'https://example.com/osaka-industrial-zone',
      '@osakaindustrialzone',
      'Osaka Industrial Zone',
      '@osakaindustrialzone',
      'Osaka Industrial Zone',
      null
    ),
    (
      'Fuji Outdoor Combat Park',
      'Gotemba',
      'Shizuoka',
      'Gotemba',
      35.3157,
      138.9381,
      'Outdoor',
      'Large outdoor field near Mt. Fuji with elevation changes and long lanes.',
      'Sniper lanes, Safe zone, Camping option, BBQ area, Pro shop',
      'Scenic views, great for all-day events',
      'Windy conditions some days',
      '+81-550-80-4455',
      'bookings@fuji-combat.jp',
      'https://example.com/fuji-outdoor-combat-park',
      '@fujicombatpark',
      'Fuji Outdoor Combat Park',
      '@fujicombatpark',
      'Fuji Outdoor Combat Park',
      null
    ),
    (
      'Nagoya Urban Strike',
      'Nagoya',
      'Aichi',
      'Nagoya',
      35.1740,
      136.9031,
      'Indoor',
      'Urban-style indoor site focused on speedsoft and short matches.',
      'Indoor map, Speedsoft nights, Tech bench, Battery charging',
      'Fast rounds, central location',
      'Can be noisy during peak hours',
      '+81-52-433-7610',
      'staff@urbanstrike-nagoya.jp',
      'https://example.com/nagoya-urban-strike',
      '@urbanstrike_nagoya',
      'Nagoya Urban Strike',
      '@urbanstrike_nagoya',
      'Nagoya Urban Strike',
      null
    ),
    (
      'Fukuoka Delta Field',
      'Fukuoka',
      'Fukuoka',
      'Fukuoka',
      33.5903,
      130.4010,
      'Mixed',
      'Balanced mixed terrain with both close-range and medium-range engagements.',
      'Mixed map, Family day events, Rental sets, Light snacks',
      'Friendly atmosphere, suitable for beginners',
      'Rain can affect outdoor lanes',
      '+81-92-710-2844',
      'delta@fukuoka-field.jp',
      'https://example.com/fukuoka-delta-field',
      '@fukuokadeltafield',
      'Fukuoka Delta Field',
      '@fukuokadeltafield',
      'Fukuoka Delta Field',
      null
    ),
    (
      'Sapporo Snow Wolf Field',
      'Sapporo',
      'Hokkaido',
      'Sapporo',
      43.0621,
      141.3544,
      'Outdoor',
      'Seasonal outdoor field with winter-safe game formats and heated rest area.',
      'Heated safe zone, Rental outerwear, Chrono checks, Parking',
      'Unique winter gameplay, helpful marshals',
      'Short daylight in winter',
      '+81-11-210-6631',
      'info@snowwolf-field.jp',
      'https://example.com/sapporo-snow-wolf-field',
      '@snowwolffield',
      'Sapporo Snow Wolf Field',
      '@snowwolffield',
      'Sapporo Snow Wolf Field',
      null
    )
) as seed(
  name,
  location_name,
  prefecture,
  city,
  latitude,
  longitude,
  field_type,
  description,
  feature_list,
  pros_list,
  cons_list,
  phone,
  email,
  website,
  instagram,
  facebook,
  x,
  youtube,
  image_url
)
where not exists (
  select 1
  from public.fields f
  where lower(f.name) = lower(seed.name)
);
