// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtvhOqpn9w0crH-3ylBLtKi_W1GfFYEI4',
    appId: '1:630959288798:android:d2337a8b9bab6ae343ed4f',
    messagingSenderId: '630959288798',
    projectId: 'airsoft-app-15023',
    storageBucket: 'airsoft-app-15023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx3jyfeLyrMo_uWLu8gEIER0pxCKfsQaQ',
    appId: '1:630959288798:ios:f5ab9646fe5b908843ed4f',
    messagingSenderId: '630959288798',
    projectId: 'airsoft-app-15023',
    storageBucket: 'airsoft-app-15023.firebasestorage.app',
    iosBundleId: 'airsoft-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx3jyfeLyrMo_uWLu8gEIER0pxCKfsQaQ',
    appId: '1:630959288798:ios:f5ab9646fe5b908843ed4f',
    messagingSenderId: '630959288798',
    projectId: 'airsoft-app-15023',
    storageBucket: 'airsoft-app-15023.firebasestorage.app',
    iosBundleId: 'airsoft-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6rsnpeT6W963LBRkMw5UGrzwzt4irvI',
    appId: '1:630959288798:web:4a2276d605506e2543ed4f',
    messagingSenderId: '630959288798',
    projectId: 'airsoft-app-15023',
    authDomain: 'airsoft-app-15023.firebaseapp.com',
    storageBucket: 'airsoft-app-15023.firebasestorage.app',
    measurementId: 'G-8TSFLMZGXT',
  );

}