import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('ja'),
  ];

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? result =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(result != null, 'No AppLocalizations found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'Airsoft App',
      'home': 'Home',
      'newsfeed': 'Newsfeed',
      'fieldFinder': 'Field Finder',
      'events': 'Events',
      'meetups': 'Meet-ups',
      'settings': 'Settings',
      'profile': 'Profile',
      'editProfile': 'Edit Profile',
      'callSign': 'Call Sign',
      'area': 'Area',
      'teamName': 'Team Name',
      'loadout': 'Loadout',
      'instagram': 'Instagram',
      'facebook': 'Facebook',
      'youtube': 'YouTube',
      'save': 'Save',
      'latestNews': 'Latest News',
      'newFields': 'New Fields',
      'newEvents': 'New Events',
      'newMeetups': 'New Meet-ups',
      'teamPosts': 'Team Creation Posts',
      'searchFields': 'Search fields',
      'searchByNameLocationType': 'Search by name, location, or type',
      'map': 'Map',
      'list': 'List',
      'calendar': 'Calendar',
      'createMeetup': 'Create Meet-up',
      'title': 'Title',
      'content': 'Content',
      'date': 'Date',
      'time': 'Time',
      'location': 'Location',
      'fontSize': 'Font Size',
      'theme': 'Theme',
      'lightMode': 'Light',
      'darkMode': 'Dark',
      'downloadUpdates': 'Download internal updates',
      'notificationSettings': 'Notification Settings',
      'privacySettings': 'Privacy Settings',
      'accountSettings': 'Account Settings',
      'language': 'Language',
      'offlineSync': 'Offline data sync',
      'fieldContact': 'Field Contact',
      'website': 'Website',
      'socialProfiles': 'Social Profiles',
      'contacts': 'Contacts',
      'messages': 'Messages',
      'addContact': 'Add Contact',
      'contactRequests': 'Contact Requests',
      'add': 'Add',
      'descriptionRequired': 'Description is required.',
      'profileAccountDetails': 'Call sign, avatar, and account details',
      'manageContactsRequests': 'Manage your contacts and requests',
      'subscription': 'Subscription',
      'free': 'Free',
        'english': 'English',
        'japanese': 'Japanese',
        'email': 'Email',
        'password': 'Password',
        'continueWith': 'Or continue with',
        'signInWithGoogle': 'Continue with Google',
        'signInWithFacebook': 'Continue with Facebook',
        'login': 'Login',
        'signUp': 'Sign Up',
        'createAccount': 'Create account',
        'signupSuccess': 'Signup successful. You can now log in.',
        'signupFailed': 'Signup failed: {error}',
        'createPost': 'Create Post',
        'section': 'Section',
        'body': 'Body',
        'bodyLinkHint': 'Links like https://example.com will be clickable.',
        'publish': 'Publish',
        'uploading': 'Uploading...',
        'addImage': 'Add Image',
        'titleRequired': 'Title is required.',
        'bodyRequired': 'Body is required.',
        'failedUploadImage': 'Failed to upload image: {error}',
        'failedCreatePost': 'Failed to create post: {error}',
        'failedLoadPosts': 'Failed to load posts: {error}',
        'searchPosts': 'Search posts',
        'boards': 'Boards',
        'newPost': 'New post',
        'newTimelinePost': 'New timeline post',
        'profileTimelineHint': 'This will be posted to your profile timeline',
        'enterTitle': 'Enter a title',
        'category': 'Category',
        'writePostHint': 'Write your post',
        'publishPost': 'Publish post',
        'postToTimeline': 'Post to timeline',
        'titleAndContentRequired': 'Title and content are required.',
        'profileNotAvailable': 'Profile not available.',
        'postLanguage': 'Post language',
        'viewLanguage': 'Reading preference',
        'bilingual': 'Bilingual',
        'allLanguages': 'All languages',
        'allPosts': 'All Posts',
        'preferEnglishPosts': 'English Posts',
        'preferJapanesePosts': 'Japanese Posts',
        'preferBilingualPosts': 'Show all languages',
        'showingAllBoardCategories': 'Showing all board categories',
        'showingCategoryPosts': 'Showing {category} posts',
        'showingPostsForLanguage': 'Showing posts for: {language}',
        'pendingNewPosts': '{count} new posts available',
        'show': 'Show',
        'noPreviewTextAvailable': 'No preview text available.',
        'pinned': 'Pinned',
        'post': 'Post',
        'noPostsFound': 'No posts found.',
        'failedLikePost': 'Failed to like post: {error}',
        'likeWithCount': 'Like {count}',
        'commentWithCount': 'Comment {count}',
        'open': 'Open',
        'failedLoadBoard': 'Failed to load board:\n{error}',
        'comments': 'Comments',
        'noCommentsYet': 'No comments yet.',
        'writeComment': 'Write a comment',
        'failedSendComment': 'Failed to send comment: {error}',
        'justNow': 'Just now',
        'now': 'Now',
        'minutesAgoShort': '{value}m ago',
        'hoursAgoShort': '{value}h ago',
        'daysAgoShort': '{value}d ago',
        'minutesShort': '{value}m',
        'hoursShort': '{value}h',
        'daysShort': '{value}d',
        'all': 'All',
        'meetupsLabel': 'Meetups',
        'techTalk': 'Tech Talk',
        'troubleshooting': 'Troubleshooting',
        'offTopic': 'Off-topic',
        'memes': 'Memes',
        'buySell': 'Buy / Sell',
        'gearShowcase': 'Gear Showcase',
        'fieldTalk': 'Field Talk',
        'createEvent': 'Create Event',
        'event': 'Event',
        'eventType': 'Event Type',
        'skillLevel': 'Skill Level',
        'locationField': 'Location / Field',
        'prefecture': 'Prefecture',
        'start': 'Start',
          'shops': 'Shops',
          'searchShopsHint': 'Search shops by name or location',
          'noShopsFound': 'No shops found.',
          'failedLoadShops': 'Failed to load shops: {error}',
          'address': 'Address',
          'addressCopied': 'Address copied',
          'openingTimes': 'Opening Times',
          'phoneNumber': 'Phone Number',
          'features': 'Features',
          'menu': 'Menu',
        'end': 'End',
        'change': 'Change',
        'priceJpy': 'Price (JPY)',
        'maxPlayers': 'Max Players',
        'organizerName': 'Organizer Name',
        'contactInfo': 'Contact Info',
        'contactInfoHint': 'Email, Instagram, LINE, etc.',
        'description': 'Description',
        'rules': 'Rules',
        'rulesNotes': 'Rules / Notes',
        'saveEvent': 'Save Event',
        'endAfterStart': 'End time must be after start time.',
        'failedCreateEvent': 'Failed to create event: {error}',
        'failedLoadEvents': 'Failed to load events:\n{error}',
        'noEventsFound': 'No events found.',
        'eventSearchHint': 'Search title, location, type, skill, organiser',
        'noMatchingEventsFound': 'No matching events found',
        'clearFilters': 'Clear filters',
        'deleteEventPromptTitle': 'Delete event?',
        'deleteEventPromptBody': 'This will permanently delete "{title}".',
        'deleteEventAction': 'Delete event',
        'deletedEvent': 'Deleted "{title}".',
        'failedDeleteEvent': 'Failed to delete event: {error}',
        'manageEvent': 'Manage event',
        'official': 'Official',
        'goingWithCount': 'Going {count}',
        'attendedWithCount': 'Attended {count}',
        'attendanceAttending': 'Attending',
        'attendanceCancelled': 'Cancelled',
        'attendanceAttended': 'Attended',
        'attendanceNoShow': 'No Show',
        'newEventCta': 'New event',
        'type': 'Type',
        'price': 'Price',
        'organizer': 'Organizer',
        'contact': 'Contact',
        'eventsComingNext': 'Events coming next',
        'findUsers': 'Find Users',
        'noContactsYet': 'No contacts yet.',
        'failedLoadContacts': 'Failed to load contacts:\n{error}',
        'operator': 'Operator',
        'noMessagesYet': 'No messages yet.',
        'failedLoadMessages': 'Failed to load messages:\n{error}',
        'dmOnlyAccepted':
          'Direct messaging is only available for accepted contacts.',
        'writeMessage': 'Write a message',
        'failedSendMessage': 'Failed to send message: {error}',
        'searchUsersHint': 'Search call sign, code, area, team',
        'noUsersFound': 'No users found.',
        'failedLoadUsers': 'Failed to load users:\n{error}',
        'contactRequestSent': 'Contact request sent to {name}.',
        'failedSendRequest': 'Failed to send request: {error}',
        'friendRequestAccepted': 'Friend request accepted',
        'failedAcceptRequest': 'Failed to accept request: {error}',
        'friends': 'Friends',
        'requestPending': 'Pending',
        'requestReceived': 'Request received',
        'notifications': 'Notifications',
        'markAllRead': 'Mark all read',
        'noNotificationsYet': 'No notifications yet.',
        'failedLoadNotifications': 'Failed to load notifications:\n{error}',
        'directMessageFallback': 'Direct Message',
        'postNoLongerAvailable': 'This post is no longer available.',
        'failedRemoveNotification': 'Failed to remove notification: {error}',
        'notificationRemoved': 'Notification removed',
        'deleteNotification': 'Delete notification',
        'failedLoadNotificationSettings':
          'Failed to load notification settings: {error}',
        'failedSaveNotificationSettings':
          'Failed to save notification settings: {error}',
        'noNotificationSettingsFound': 'No notification settings found.',
        'newEventsLabel': 'New Events',
        'meetupActivity': 'Meetup Activity',
        'directMessages': 'Direct Messages',
        'fieldUpdates': 'Field Updates',
        'newEventsSubtitle': 'Get notified when new events go live',
        'meetupActivitySubtitle': 'Get notified about meetup updates',
        'directMessagesSubtitle': 'Get notified when someone messages you',
        'fieldUpdatesSubtitle': 'Get notified about field changes and news',
        'edit': 'Edit',
        'saveChanges': 'Save changes',
        'failedSaveProfile': 'Failed to save profile: {error}',
        'avatarUpdated': 'Avatar updated.',
        'avatarUpdateFailed': 'Avatar update failed: {error}',
        'updating': 'Updating...',
        'changeAvatar': 'Change Avatar',
        'cropAvatar': 'Crop Avatar',
        'noProfileAvailable': 'No profile available.',
        'profileError': 'Profile error:\n{error}',
        'signedInAccount': 'Signed-in account',
        'display': 'Display',
        'lightDarkControls': 'Light and dark display controls',
        'pushNotifications': 'Push Notifications',
        'manageAlerts': 'Manage event, board, DM, and field alerts',
        'privacy': 'Privacy',
        'privacyControls': 'Privacy Controls',
        'profileVisibilityPermissions':
          'Profile visibility and interaction permissions',
        'blockedUsers': 'Blocked Users',
        'manageBlockedAccounts': 'Manage blocked accounts',
        'account': 'Account',
        'viewSignedInEmail': 'View your signed-in email account',
        'logout': 'Logout',
        'logoutFailed': 'Logout failed: {error}',
        'logoutConfirmMessage': 'Do you want to sign out of your account?',
        'cancel': 'Cancel',
        'displayThemeSubtitle': 'Dark theme currently active',
        'fontSizePlaceholder': 'Font size control placeholder',
        'showAreaProfile': 'Show area on profile',
        'showTeamProfile': 'Show team name on profile',
        'allowDirectMessages': 'Allow direct messages',
        'newEventNotifications': 'New event notifications',
        'meetupActivityNotifications': 'Meet-up activity notifications',
        'directMessageNotifications': 'Direct message notifications',
        'fieldUpdateNotifications': 'Field update notifications',
        'searchFieldsHint': 'Search by field name or location',
        'fieldType': 'Field Type',
        'minRating': 'Min Rating',
        'any': 'Any',
        'noRating': 'No rating',
        'noRatingYet': 'No rating yet',
        'noDescriptionAvailable': 'No description available.',
        'coordinates': 'Coordinates',
        'openInMaps': 'Open in Maps',
        'failedOpenMapApp': 'Could not open map app.',
        'reviewPosted': 'Review posted',
        'failedPostReview': 'Failed to post review: {error}',
        'fieldFallbackName': 'Field',
        'mapViewPlaceholder': 'Map view placeholder',
        'failedLoadFields': 'Failed to load fields: {error}',
        'noFieldsFound': 'No fields found.',
        'fieldMap': 'Field Map',
        'board': 'Board',
        'fieldOps': 'FieldOps',
        'editEvent': 'Edit Event',
        'updateEvent': 'Update Event',
        'createOfficialEvent': 'Create Official Event',
        'updateOfficialEvent': 'Update Official Event',
        'officialFieldListing': 'Official Field Listing',
        'editField': 'Edit Field',
        'createOfficialField': 'Create Official Field',
        'updateOfficialField': 'Update Official Field',
        'fieldName': 'Field name',
        'locationName': 'Location name',
        'city': 'City',
        'imageUrl': 'Image URL',
        'latitude': 'Latitude',
        'longitude': 'Longitude',
        'fieldRequiredValues': 'Name, location, description, latitude and longitude are required.',
        'failedCreateField': 'Failed to create field: {error}',
        'failedUpdateField': 'Failed to update field: {error}',
        'manageOfficialContent': 'Manage official events and fields.',
        'recentEvents': 'Recent Events',
        'recentFields': 'Recent Fields',
        'send': 'Send',
        'delete': 'Delete',
        'remove': 'Remove',
        'report': 'Report',
        'reportUser': 'Report user',
        'reportContent': 'Report content',
        'submitReport': 'Submit report',
        'reportSubmitted': 'Report submitted. Our moderators will review it.',
        'reason': 'Reason',
        'detailsOptional': 'Details (optional)',
        'other': 'Other',
        'reportReasonSpam': 'Spam',
        'reportReasonHarassment': 'Harassment',
        'reportReasonHate': 'Hate speech',
        'reportReasonScam': 'Scam or fraud',
        'mustBeLoggedInToReport': 'Please log in to submit a report.',
        'muteUser': 'Mute user',
        'blockUser': 'Block user',
        'userMuted': 'User muted.',
        'userBlocked': 'User blocked.',
        'userUnmuted': 'User unmuted.',
        'userUnblocked': 'User unblocked.',
        'mutedUsers': 'Muted Users',
        'noBlockedUsers': 'No blocked users.',
        'noMutedUsers': 'No muted users.',
        'blockedOn': 'Blocked on',
        'mutedOn': 'Muted on',
        'expires': 'Expires',
        'noExpiry': 'No expiry',
        'unblock': 'Unblock',
        'unmute': 'Unmute',
        'reply': 'Reply',
        'comment': 'Comment',
        'retry': 'Retry',
        'discussion': 'Discussion',
        'media': 'Media',
        'author': 'Author',
        'posted': 'Posted',
        'edited': 'Edited',
        'copyPost': 'Copy post',
        'copyComment': 'Copy comment',
        'commentCopied': 'Comment copied',
        'fullPostCopied': 'Full post copied to clipboard',
        'showAllThreads': 'Show all threads',
        'commentsWithCount': 'Comments ({count})',
        'mediaWithCount': 'Media ({count})',
        'mostRecentComments': 'Most recent',
        'allComments': 'All comments',
        'popularComments': 'Popular comments',
        'replyingTo': 'Replying to {name}',
        'inReplyTo': 'Reply to {name}',
        'cancelReply': 'Cancel reply',
        'uploadImage': 'Upload image',
        'removeImage': 'Remove image',
        'noImagesAttachedToPost': 'No images attached to this post.',
        'noContentAvailable': 'No content available.',
        'postNotFound': 'Post not found',
        'failedLoadPost': 'Failed to load post: {error}',
        'failedPostComment': 'Failed to post comment: {error}',
        'failedUpdateLike': 'Failed to update like: {error}',
        'failedUpdateCommentLike': 'Failed to update comment like: {error}',
        'editPost': 'Edit post',
        'failedUpdatePost': 'Failed to update post: {error}',
        'deletePostTitle': 'Delete post?',
        'deletePostBody': 'This will remove your post from the feed.',
        'failedDeletePost': 'Failed to delete post: {error}',
        'editComment': 'Edit comment',
        'failedUpdateComment': 'Failed to update comment: {error}',
        'deleteCommentTitle': 'Delete comment?',
        'deleteCommentBody': 'This will remove your comment.',
        'failedDeleteComment': 'Failed to delete comment: {error}',
        'swipeForMore': 'Swipe for more',
        'failedLoadEvent': 'Failed to load event: {error}',
        'failedConfirmAttendance': 'Failed to confirm attendance: {error}',
        'failedCancelAttendance': 'Failed to cancel attendance: {error}',
        'failedUpdateAttendee': 'Failed to update attendee: {error}',
        'deleteEventDetailsBody': 'This will permanently delete this event.',
        'mustBeLoggedInToComment': 'You must be logged in to comment.',
        'attendance': 'Attendance',
        'cancelledWithCount': 'Cancelled {count}',
        'youAreAttendingEvent': 'You are marked as attending this event.',
        'youCancelledAttendance': 'You have cancelled your attendance.',
        'attendInstead': 'Attend Instead',
        'hostConfirmedAttended':
          'The host has confirmed you attended this event.',
        'attendanceConfirmed': 'Attendance Confirmed',
        'hostMarkedNoShow': 'The host marked you as not attended.',
        'markAttendingAgain': 'Mark Attending Again',
        'letHostKnowGoing': 'Let the host know you are going.',
        'attend': 'Attend',
        'hostControls': 'Host Controls',
        'confirmAttendeesHelp': 'Confirm whether attendees actually showed up.',
        'noAttendeesYet': 'No attendees yet.',
        'statusLabel': 'Status: {status}',
        'markAttended': 'Mark Attended',
        'markNoShow': 'Mark No Show',
        'reset': 'Reset',
        'attendees': 'Attendees',
        'peopleGoingCount': 'People going: {count}',
        'logInToJoinConversation': 'Log in to join the conversation.',
        'unsend': 'Unsend',
        'deleteMessage': 'Delete message',
        'actionFailed': 'Action failed: {error}',
        'readReceipts': 'Read receipts',
        'expirePhotoMessages30d': 'Expire photo messages in 30 days',
        'messageUnsent': '[Message unsent]',
        'addPhoto': 'Add photo',
        'officialEvent': 'Official Event',
        'forgotPassword': 'Forgot password',
        'forgotPasswordPrompt':
          'Enter your email address and we will send a password reset link.',
        'forgotPasswordQuestion': 'Forgot password?',
        'sendResetLink': 'Send reset link',
        'passwordResetSent': 'Password reset email sent. Check your inbox.',
        'couldNotOpenBlogPost': 'Could not open blog post',
        'couldNotOpenBlog': 'Could not open blog',
        'recentPosts': 'Recent Posts',
        'recentPostsSubtitle': 'What members are talking about now',
        'noPostsYet': 'No posts yet',
        'friendsTimeline': 'Friends Timeline',
        'friendsTimelineSubtitle': 'Latest timeline posts from your friends',
        'noFriendTimelinePostsYet': 'No friend timeline posts yet',
        'closestEventsSoon': 'Closest events happening soon',
        'noUpcomingEvents': 'No upcoming events',
        'airsoftBlog': 'Airsoft Blog',
        'airsoftBlogSubtitle': 'Latest posts from airsoftonlinejapan.com/blog',
        'noBlogPostsFound': 'No blog posts found',
        'fieldOpsNewsFeed': 'FieldOps News Feed',
        'blog': 'Blog',
        'viewAll': 'View all',
        'locationTbd': 'Location TBD',
        'openArticle': 'Open article',
        // ── Membership ──────────────────────────────────────────────────────
        'annualMembership': 'Ad-free membership',
        'annualPlan': 'Google Play payment: ¥800',
        'membershipProcess': 'Process: submit request → admin review → Google Play payment → ads removed after activation.',
        'membershipFullName': 'Full name',
        'membershipContactEmail': 'Contact email',
        'membershipNotesHint': 'Notes for admin (optional)',
        'membershipSubmitting': 'Submitting...',
        'membershipRequestBtn': 'Request ad-free membership',
        'membershipRequestSent': 'Request sent. Admin will review first, then send a Google Play payment request for ¥800 if approved.',
        'membershipSubmitFailed': 'Could not submit request: {error}',
        'membershipNameEmailRequired': 'Please provide your name and email.',
        'membershipStatusNone': 'No active request',
        'membershipStatusPending': 'Pending review',
        'membershipStatusApproved': 'Approved',
        'membershipStatusRejected': 'Rejected',
        'membershipStatusPaymentRequested': 'Payment requested',
        'membershipStatusActive': 'Active',
        'membershipStatusExpired': 'Expired',
        'membershipAdminNote': 'Admin note: {note}',
        'membershipExpires': 'Expires: {date}',
        // ── Team Map ─────────────────────────────────────────────────────────
        'teamMap': '{teamName} Map',
        'tacticalMap': 'Tactical Map',
        'uploadMap': 'Upload map',
        'createTacticalMap': 'Create tactical map',
        'mapTitle': 'Map title',
        'noTeamMapsYet': 'No team maps yet. Upload a tactical image map to start plotting respawns, targets, and routes.',
        'createFirstMap': 'Create first map',
        'uploadMapBtn': 'Upload',
        'mapUploadSuccess': 'Map uploaded and shared with team.',
        'mapUploadFailed': 'Failed to create map: {error}',
        'addMarkerFailed': 'Failed to add marker: {error}',
        'routeSaved': 'Route saved to team map.',
        'routeSaveFailed': 'Failed to save route: {error}',
        'mapModeRespawn': 'Respawn',
        'mapModeTarget': 'Target',
        'mapModeObjective': 'Objective',
        'mapModeWaypoint': 'Waypoint',
        'mapModeRoute': 'Route',
        'mapModeClear': 'Clear',
        'mapSaveRoute': 'Save',
        'mapToolsLabel': 'Tools',
        'addLabel': 'Add label',
        'skip': 'Skip',
        'done': 'Done',
        'teamChat': 'Team Chat',
        // ── Team Chat ────────────────────────────────────────────────────────
        'teamChatTitle': '{teamName} Chat',
        'noTeamMessagesYet': 'No team messages yet. Start the conversation.',
        'teamMessageHint': 'Message your team in real-time',
        'teamMessageSendFailed': 'Failed to send message: {error}',
        // User listing submissions
        'submitField': 'Submit a Field',
        'submitShop': 'Submit a Shop',
        'submitListingHint': 'Your submission will be reviewed by an admin before it becomes publicly visible.',
        'submitListingBtn': 'Submit for Review',
        'submitListingSuccess': 'Submitted! An admin will review your listing.',
        'submitListingFailed': 'Submission failed: {error}',
        'submitListingNameLocationRequired': 'Name and location name are required.',
        'submitShopNameAddressRequired': 'Name and address are required.',
        'invalidLatLng': 'Latitude and longitude must be valid numbers.',
        'mySubmissions': 'My Submissions',
        'noSubmissionsYet': 'You have no submissions yet.',
        'statusPending': 'Pending',
        'statusApproved': 'Approved',
        'statusRejected': 'Rejected',
        'fieldNameLabel': 'Field Name',
        'shopNameLabel': 'Shop Name',
    },
    'ja': {
      'appTitle': 'エアソフトアプリ',
      'home': 'ホーム',
      'newsfeed': 'ニュースフィード',
      'fieldFinder': 'フィールド検索',
      'events': 'イベント',
      'meetups': '交流募集',
      'settings': '設定',
      'profile': 'プロフィール',
      'editProfile': 'プロフィール編集',
      'callSign': 'コールサイン',
      'area': '活動エリア',
      'teamName': 'チーム名',
      'loadout': '装備',
      'instagram': 'インスタグラム',
      'facebook': 'フェイスブック',
      'youtube': 'ユーチューブ',
      'save': '保存',
      'latestNews': '最新ニュース',
      'newFields': '新着フィールド',
      'newEvents': '新着イベント',
      'newMeetups': '新着交流募集',
      'teamPosts': 'チーム募集投稿',
      'searchFields': 'フィールド検索',
      'searchByNameLocationType': '名前、場所、種別で検索',
      'map': '地図',
      'list': '一覧',
      'calendar': 'カレンダー',
      'createMeetup': '交流募集を作成',
      'title': 'タイトル',
      'content': '内容',
      'date': '日付',
      'time': '時間',
      'location': '場所',
      'fontSize': '文字サイズ',
      'theme': 'テーマ',
      'lightMode': 'ライト',
      'darkMode': 'ダーク',
      'downloadUpdates': '内部更新をダウンロード',
      'notificationSettings': '通知設定',
      'privacySettings': 'プライバシー設定',
      'accountSettings': 'アカウント設定',
      'language': '言語',
      'offlineSync': 'オフライン同期',
      'fieldContact': 'フィールド連絡先',
      'website': 'ウェブサイト',
      'socialProfiles': 'SNSプロフィール',
      'contacts': '連絡先',
      'messages': 'メッセージ',
      'addContact': '連絡先追加',
      'contactRequests': 'リクエスト',
      'add': '追加',
      'descriptionRequired': '説明は必須です。',
      'profileAccountDetails': 'コールサイン、アバター、アカウント情報',
      'manageContactsRequests': '連絡先とリクエストを管理',
      'subscription': 'サブスクリプション',
      'free': '無料',
      'english': '英語',
      'japanese': '日本語',
      'email': 'メールアドレス',
      'password': 'パスワード',
      'continueWith': 'または次で続行',
      'signInWithGoogle': 'Googleで続行',
      'signInWithFacebook': 'Facebookで続行',
      'login': 'ログイン',
      'signUp': '新規登録',
      'createAccount': 'アカウント作成',
      'signupSuccess': '登録が完了しました。ログインできます。',
      'signupFailed': '登録に失敗しました: {error}',
      'createPost': '投稿を作成',
      'section': 'セクション',
      'body': '本文',
      'bodyLinkHint': 'https://example.com のようなリンクはタップできます。',
      'publish': '公開',
      'uploading': 'アップロード中...',
      'addImage': '画像を追加',
      'titleRequired': 'タイトルは必須です。',
      'bodyRequired': '本文は必須です。',
      'failedUploadImage': '画像のアップロードに失敗しました: {error}',
      'failedCreatePost': '投稿の作成に失敗しました: {error}',
      'failedLoadPosts': '投稿の読み込みに失敗しました: {error}',
      'searchPosts': '投稿を検索',
      'boards': '掲示板',
      'newPost': '新しい投稿',
      'newTimelinePost': 'タイムライン投稿',
      'profileTimelineHint': 'この投稿はプロフィールのタイムラインに表示されます',
      'enterTitle': 'タイトルを入力',
      'category': 'カテゴリ',
      'writePostHint': '投稿内容を入力してください',
      'publishPost': '投稿を公開',
      'postToTimeline': 'タイムラインに投稿',
      'titleAndContentRequired': 'タイトルと内容は必須です。',
      'profileNotAvailable': 'プロフィールを開けません。',
      'postLanguage': '投稿言語',
      'viewLanguage': '表示言語の好み',
      'bilingual': 'バイリンガル',
      'allLanguages': 'すべての言語',
      'allPosts': 'すべての投稿',
      'preferEnglishPosts': '英語の投稿',
      'preferJapanesePosts': '日本語の投稿',
      'preferBilingualPosts': 'すべての言語を表示',
      'showingAllBoardCategories': 'すべてのカテゴリを表示中',
      'showingCategoryPosts': '{category} の投稿を表示中',
      'showingPostsForLanguage': '{language} 向けの投稿を表示中',
      'pendingNewPosts': '{count}件の新しい投稿があります',
      'show': '表示',
      'noPreviewTextAvailable': 'プレビューできる本文はありません。',
      'pinned': '固定',
      'post': '投稿',
      'noPostsFound': '投稿が見つかりません。',
      'failedLikePost': '投稿へのいいねに失敗しました: {error}',
      'likeWithCount': 'いいね {count}',
      'commentWithCount': 'コメント {count}',
      'open': '開く',
      'failedLoadBoard': '掲示板の読み込みに失敗しました:\n{error}',
      'comments': 'コメント',
      'noCommentsYet': 'まだコメントはありません。',
      'writeComment': 'コメントを書く',
      'failedSendComment': 'コメント送信に失敗しました: {error}',
      'justNow': 'たった今',
      'now': '今',
      'minutesAgoShort': '{value}分前',
      'hoursAgoShort': '{value}時間前',
      'daysAgoShort': '{value}日前',
      'minutesShort': '{value}分',
      'hoursShort': '{value}時間',
      'daysShort': '{value}日',
      'all': 'すべて',
      'meetupsLabel': '交流募集',
      'techTalk': '技術トーク',
      'troubleshooting': 'トラブル相談',
      'offTopic': '雑談',
      'memes': 'ミーム',
      'buySell': '売買',
      'gearShowcase': '装備紹介',
      'fieldTalk': 'フィールド雑談',
      'createEvent': 'イベント作成',
      'event': 'イベント',
      'eventType': 'イベント種別',
      'skillLevel': 'レベル',
      'locationField': '場所 / フィールド',
      'prefecture': '都道府県',
        'shops': 'ショップ',
        'searchShopsHint': 'ショップを検索',
        'noShopsFound': 'ショップが見つかりません。',
        'failedLoadShops': 'ショップの読み込みに失敗しました: {error}',
        'address': '住所',
        'addressCopied': '住所をコピーしました',
        'openingTimes': '営業時間',
        'phoneNumber': '電話番号',
        'features': '特徴',
        'menu': 'メニュー',
      'start': '開始',
      'end': '終了',
      'change': '変更',
      'priceJpy': '料金 (円)',
      'maxPlayers': '最大人数',
      'organizerName': '主催者名',
      'contactInfo': '連絡先',
      'contactInfoHint': 'メール、Instagram、LINE など',
      'description': '説明',
      'rules': 'ルール',
      'rulesNotes': 'ルール / 注意事項',
      'saveEvent': 'イベントを保存',
      'endAfterStart': '終了時刻は開始時刻より後にしてください。',
      'failedCreateEvent': 'イベント作成に失敗しました: {error}',
      'failedLoadEvents': 'イベントの読み込みに失敗しました:\n{error}',
      'noEventsFound': 'イベントが見つかりません。',
      'eventSearchHint': 'タイトル、場所、種別、スキル、主催者で検索',
      'noMatchingEventsFound': '一致するイベントが見つかりません',
      'clearFilters': 'フィルターをクリア',
      'deleteEventPromptTitle': 'イベントを削除しますか？',
      'deleteEventPromptBody': '「{title}」を完全に削除します。',
      'deleteEventAction': 'イベントを削除',
      'deletedEvent': '「{title}」を削除しました。',
      'failedDeleteEvent': 'イベントの削除に失敗しました: {error}',
      'manageEvent': 'イベントを管理',
      'official': '公式',
      'goingWithCount': '参加予定 {count}',
      'attendedWithCount': '参加済み {count}',
      'attendanceAttending': '参加予定',
      'attendanceCancelled': 'キャンセル',
      'attendanceAttended': '参加済み',
      'attendanceNoShow': '不参加',
      'newEventCta': '新しいイベント',
      'type': '種別',
      'price': '料金',
      'organizer': '主催',
      'contact': '連絡先',
      'eventsComingNext': 'まもなくイベント機能を公開します',
      'findUsers': 'ユーザー検索',
      'noContactsYet': '連絡先はまだありません。',
      'failedLoadContacts': '連絡先の読み込みに失敗しました:\n{error}',
      'operator': 'オペレーター',
      'noMessagesYet': 'メッセージはまだありません。',
      'failedLoadMessages': 'メッセージの読み込みに失敗しました:\n{error}',
      'dmOnlyAccepted': 'ダイレクトメッセージは承認済み連絡先のみ利用できます。',
      'writeMessage': 'メッセージを書く',
      'failedSendMessage': 'メッセージ送信に失敗しました: {error}',
      'searchUsersHint': 'コールサイン、コード、エリア、チームで検索',
      'noUsersFound': 'ユーザーが見つかりません。',
      'failedLoadUsers': 'ユーザーの読み込みに失敗しました:\n{error}',
      'contactRequestSent': '{name} に連絡先リクエストを送信しました。',
      'failedSendRequest': 'リクエスト送信に失敗しました: {error}',
      'friendRequestAccepted': 'フレンドリクエストを承認しました',
      'failedAcceptRequest': 'リクエスト承認に失敗しました: {error}',
      'friends': 'フレンド',
      'requestPending': '保留中',
      'requestReceived': 'リクエスト受信',
      'notifications': '通知',
      'markAllRead': 'すべて既読',
      'noNotificationsYet': '通知はまだありません。',
      'failedLoadNotifications': '通知の読み込みに失敗しました:\n{error}',
      'directMessageFallback': 'ダイレクトメッセージ',
      'postNoLongerAvailable': 'この投稿は利用できなくなりました。',
      'failedRemoveNotification': '通知の削除に失敗しました: {error}',
      'notificationRemoved': '通知を削除しました',
      'deleteNotification': '通知を削除',
      'failedLoadNotificationSettings': '通知設定の読み込みに失敗しました: {error}',
      'failedSaveNotificationSettings': '通知設定の保存に失敗しました: {error}',
      'noNotificationSettingsFound': '通知設定が見つかりません。',
      'newEventsLabel': '新着イベント',
      'meetupActivity': '交流募集のアクティビティ',
      'directMessages': 'ダイレクトメッセージ',
      'fieldUpdates': 'フィールド更新',
      'newEventsSubtitle': '新しいイベント公開時に通知を受け取る',
      'meetupActivitySubtitle': '交流募集の更新通知を受け取る',
      'directMessagesSubtitle': 'メッセージ受信時に通知を受け取る',
      'fieldUpdatesSubtitle': 'フィールド変更やニュースの通知を受け取る',
      'edit': '編集',
      'saveChanges': '変更を保存',
      'failedSaveProfile': 'プロフィール保存に失敗しました: {error}',
      'avatarUpdated': 'アバターを更新しました。',
      'avatarUpdateFailed': 'アバター更新に失敗しました: {error}',
      'updating': '更新中...',
      'changeAvatar': 'アバターを変更',
      'cropAvatar': 'アバターを切り抜き',
      'noProfileAvailable': 'プロフィールがありません。',
      'profileError': 'プロフィールエラー:\n{error}',
      'signedInAccount': 'ログイン中のアカウント',
      'display': '表示',
      'lightDarkControls': 'ライト/ダーク表示を設定',
      'pushNotifications': 'プッシュ通知',
      'manageAlerts': 'イベント、掲示板、DM、フィールド通知を管理',
      'privacy': 'プライバシー',
      'privacyControls': 'プライバシー管理',
      'profileVisibilityPermissions': 'プロフィール公開範囲と操作権限',
      'blockedUsers': 'ブロックしたユーザー',
      'manageBlockedAccounts': 'ブロック中アカウントを管理',
      'account': 'アカウント',
      'viewSignedInEmail': 'ログイン中メールアカウントを表示',
      'logout': 'ログアウト',
      'logoutFailed': 'ログアウトに失敗しました: {error}',
      'logoutConfirmMessage': 'アカウントからサインアウトしますか？',
      'cancel': 'キャンセル',
      'displayThemeSubtitle': '現在はダークテーマです',
      'fontSizePlaceholder': '文字サイズ調整のプレースホルダー',
      'showAreaProfile': 'プロフィールにエリアを表示',
      'showTeamProfile': 'プロフィールにチーム名を表示',
      'allowDirectMessages': 'ダイレクトメッセージを許可',
      'newEventNotifications': '新規イベント通知',
      'meetupActivityNotifications': '交流募集アクティビティ通知',
      'directMessageNotifications': 'ダイレクトメッセージ通知',
      'fieldUpdateNotifications': 'フィールド更新通知',
      'searchFieldsHint': 'フィールド名または場所で検索',
      'fieldType': 'フィールド種別',
      'minRating': '最低評価',
      'any': '指定なし',
      'noRating': '評価なし',
      'noRatingYet': 'まだ評価がありません',
      'noDescriptionAvailable': '説明はまだありません。',
      'coordinates': '座標',
      'openInMaps': '地図で開く',
      'failedOpenMapApp': '地図アプリを開けませんでした。',
      'reviewPosted': 'レビューを投稿しました',
      'failedPostReview': 'レビュー投稿に失敗しました: {error}',
      'fieldFallbackName': 'フィールド',
      'mapViewPlaceholder': '地図ビュー準備中',
      'failedLoadFields': 'フィールドの読み込みに失敗しました: {error}',
      'noFieldsFound': 'フィールドが見つかりません。',
      'fieldMap': 'フィールドマップ',
      'board': '掲示板',
      'fieldOps': 'フィールドオプス',
      'editEvent': 'イベントを編集',
      'updateEvent': 'イベントを更新',
      'createOfficialEvent': '公式イベントを作成',
      'updateOfficialEvent': '公式イベントを更新',
      'officialFieldListing': '公式フィールド登録',
      'editField': 'フィールドを編集',
      'createOfficialField': '公式フィールドを作成',
      'updateOfficialField': '公式フィールドを更新',
      'fieldName': 'フィールド名',
      'locationName': '場所名',
      'city': '市区町村',
      'imageUrl': '画像URL',
      'latitude': '緯度',
      'longitude': '経度',
      'fieldRequiredValues': '名前、場所、説明、緯度、経度は必須です。',
      'failedCreateField': 'フィールド作成に失敗しました: {error}',
      'failedUpdateField': 'フィールド更新に失敗しました: {error}',
      'manageOfficialContent': '公式イベントとフィールドを管理します。',
      'recentEvents': '最近のイベント',
      'recentFields': '最近のフィールド',
      'send': '送信',
      'delete': '削除',
      'remove': '削除',
      'report': '通報',
      'reportUser': 'ユーザーを通報',
      'reportContent': 'コンテンツを通報',
      'submitReport': '通報を送信',
      'reportSubmitted': '通報を送信しました。モデレーターが確認します。',
      'reason': '理由',
      'detailsOptional': '詳細（任意）',
      'other': 'その他',
      'reportReasonSpam': 'スパム',
      'reportReasonHarassment': '嫌がらせ',
      'reportReasonHate': 'ヘイト表現',
      'reportReasonScam': '詐欺',
      'mustBeLoggedInToReport': '通報するにはログインしてください。',
      'muteUser': 'ユーザーをミュート',
      'blockUser': 'ユーザーをブロック',
      'userMuted': 'ユーザーをミュートしました。',
      'userBlocked': 'ユーザーをブロックしました。',
      'userUnmuted': 'ユーザーのミュートを解除しました。',
      'userUnblocked': 'ユーザーのブロックを解除しました。',
      'mutedUsers': 'ミュートしたユーザー',
      'noBlockedUsers': 'ブロック中のユーザーはいません。',
      'noMutedUsers': 'ミュート中のユーザーはいません。',
      'blockedOn': 'ブロック日時',
      'mutedOn': 'ミュート日時',
      'expires': '期限',
      'noExpiry': '期限なし',
      'unblock': 'ブロック解除',
      'unmute': 'ミュート解除',
      'reply': '返信',
      'comment': 'コメント',
      'retry': '再試行',
      'discussion': 'ディスカッション',
      'media': 'メディア',
      'author': '投稿者',
      'posted': '投稿日',
      'edited': '編集済み',
      'copyPost': '投稿をコピー',
      'copyComment': 'コメントをコピー',
      'commentCopied': 'コメントをコピーしました',
      'fullPostCopied': '投稿全文をクリップボードにコピーしました',
      'showAllThreads': 'すべてのスレッドを表示',
      'commentsWithCount': 'コメント ({count})',
      'mediaWithCount': 'メディア ({count})',
      'mostRecentComments': '最新順',
      'allComments': 'すべてのコメント',
      'popularComments': '人気のコメント',
      'replyingTo': '{name} に返信中',
      'inReplyTo': '{name} への返信',
      'cancelReply': '返信をキャンセル',
      'uploadImage': '画像をアップロード',
      'removeImage': '画像を削除',
      'noImagesAttachedToPost': 'この投稿には画像がありません。',
      'noContentAvailable': '表示できる内容がありません。',
      'postNotFound': '投稿が見つかりません',
      'failedLoadPost': '投稿の読み込みに失敗しました: {error}',
      'failedPostComment': 'コメントの投稿に失敗しました: {error}',
      'failedUpdateLike': 'いいねの更新に失敗しました: {error}',
      'failedUpdateCommentLike': 'コメントいいねの更新に失敗しました: {error}',
      'editPost': '投稿を編集',
      'failedUpdatePost': '投稿の更新に失敗しました: {error}',
      'deletePostTitle': '投稿を削除しますか？',
      'deletePostBody': 'この投稿をフィードから削除します。',
      'failedDeletePost': '投稿の削除に失敗しました: {error}',
      'editComment': 'コメントを編集',
      'failedUpdateComment': 'コメントの更新に失敗しました: {error}',
      'deleteCommentTitle': 'コメントを削除しますか？',
      'deleteCommentBody': 'このコメントを削除します。',
      'failedDeleteComment': 'コメントの削除に失敗しました: {error}',
      'swipeForMore': 'スワイプで次の画像へ',
      'failedLoadEvent': 'イベントの読み込みに失敗しました: {error}',
      'failedConfirmAttendance': '参加確定に失敗しました: {error}',
      'failedCancelAttendance': '参加キャンセルに失敗しました: {error}',
      'failedUpdateAttendee': '参加者の更新に失敗しました: {error}',
      'deleteEventDetailsBody': 'このイベントを完全に削除します。',
      'mustBeLoggedInToComment': 'コメントするにはログインが必要です。',
      'attendance': '参加状況',
      'cancelledWithCount': 'キャンセル {count}',
      'youAreAttendingEvent': 'このイベントに参加予定として登録されています。',
      'youCancelledAttendance': '参加をキャンセルしました。',
      'attendInstead': '参加予定に戻す',
      'hostConfirmedAttended': '主催者があなたを参加済みとして確認しました。',
      'attendanceConfirmed': '参加確認済み',
      'hostMarkedNoShow': '主催者により不参加として記録されました。',
      'markAttendingAgain': '参加予定に戻す',
      'letHostKnowGoing': '参加予定であることを主催者に知らせましょう。',
      'attend': '参加する',
      'hostControls': '主催者コントロール',
      'confirmAttendeesHelp': '参加者の実参加を確認します。',
      'noAttendeesYet': '参加者はまだいません。',
      'statusLabel': '状態: {status}',
      'markAttended': '参加済みにする',
      'markNoShow': '不参加にする',
      'reset': 'リセット',
      'attendees': '参加者',
      'peopleGoingCount': '参加予定: {count}人',
      'logInToJoinConversation': '会話に参加するにはログインしてください。',
      'unsend': '送信取り消し',
      'deleteMessage': 'メッセージを削除',
      'actionFailed': '操作に失敗しました: {error}',
      'readReceipts': '既読表示',
      'expirePhotoMessages30d': '写真メッセージを30日で期限切れにする',
      'messageUnsent': '[メッセージを取り消しました]',
      'addPhoto': '写真を追加',
      'officialEvent': '公式イベント',
      'forgotPassword': 'パスワードを忘れた場合',
      'forgotPasswordPrompt':
          'メールアドレスを入力すると、パスワード再設定リンクを送信します。',
      'forgotPasswordQuestion': 'パスワードをお忘れですか？',
      'sendResetLink': '再設定リンクを送信',
      'passwordResetSent': 'パスワード再設定メールを送信しました。受信箱を確認してください。',
      'couldNotOpenBlogPost': 'ブログ記事を開けませんでした',
      'couldNotOpenBlog': 'ブログを開けませんでした',
      'recentPosts': '最近の投稿',
      'recentPostsSubtitle': 'メンバーの最新トーク',
      'noPostsYet': '投稿はまだありません',
      'friendsTimeline': 'フレンドタイムライン',
      'friendsTimelineSubtitle': 'フレンドの最新タイムライン投稿',
      'noFriendTimelinePostsYet': 'フレンドのタイムライン投稿はまだありません',
      'closestEventsSoon': 'まもなく開催されるイベント',
      'noUpcomingEvents': '今後のイベントはありません',
      'airsoftBlog': 'エアソフトブログ',
      'airsoftBlogSubtitle': 'airsoftonlinejapan.com/blog の最新記事',
      'noBlogPostsFound': 'ブログ記事が見つかりません',
      'fieldOpsNewsFeed': 'FieldOps ニュースフィード',
      'blog': 'ブログ',
      'viewAll': 'すべて見る',
      'locationTbd': '場所未定',
      'openArticle': '記事を開く',
      // ── Membership ──────────────────────────────────────────────────────
      'annualMembership': '広告非表示 メンバーシップ',
      'annualPlan': 'Google Play 決済: ¥800',
      'membershipProcess': '手順: リクエスト送信 → 管理者審査 → Google Play 決済 → 有効化後に広告非表示',
      'membershipFullName': '氏名',
      'membershipContactEmail': '連絡用メールアドレス',
      'membershipNotesHint': '管理者へのメモ（任意）',
      'membershipSubmitting': '送信中...',
      'membershipRequestBtn': '広告非表示メンバーシップを申請',
      'membershipRequestSent': 'リクエストを送信しました。承認後、管理者よりGoogle Play決済リクエスト（¥800）が届きます。',
      'membershipSubmitFailed': 'リクエストを送信できませんでした: {error}',
      'membershipNameEmailRequired': '氏名とメールアドレスを入力してください。',
      'membershipStatusNone': 'リクエストなし',
      'membershipStatusPending': '審査待ち',
      'membershipStatusApproved': '承認済み',
      'membershipStatusRejected': '却下',
      'membershipStatusPaymentRequested': '決済リクエスト済み',
      'membershipStatusActive': '有効',
      'membershipStatusExpired': '期限切れ',
      'membershipAdminNote': '管理者メモ: {note}',
      'membershipExpires': '有効期限: {date}',
      // ── Team Map ─────────────────────────────────────────────────────────
      'teamMap': '{teamName} マップ',
      'tacticalMap': 'タクティカルマップ',
      'uploadMap': 'マップをアップロード',
      'createTacticalMap': 'タクティカルマップを作成',
      'mapTitle': 'マップタイトル',
      'noTeamMapsYet': 'マップがまだありません。戦術マップ画像をアップロードして、リスポーン・目標・ルートを計画しましょう。',
      'createFirstMap': '最初のマップを作成',
      'uploadMapBtn': 'アップロード',
      'mapUploadSuccess': 'マップをアップロードしてチームに共有しました。',
      'mapUploadFailed': 'マップの作成に失敗しました: {error}',
      'addMarkerFailed': 'マーカーの追加に失敗しました: {error}',
      'routeSaved': 'ルートをチームマップに保存しました。',
      'routeSaveFailed': 'ルートの保存に失敗しました: {error}',
      'mapModeRespawn': 'リスポーン',
      'mapModeTarget': 'ターゲット',
      'mapModeObjective': '目標',
      'mapModeWaypoint': 'ウェイポイント',
      'mapModeRoute': 'ルート',
      'mapModeClear': 'クリア',
      'mapSaveRoute': '保存',
      'addLabel': 'ラベルを追加',
      'skip': 'スキップ',
      'done': '完了',
      'mapToolsLabel': 'ツール',
      'teamChat': 'チャット',
      // ── Team Chat ────────────────────────────────────────────────────────
      'teamChatTitle': '{teamName} チャット',
      'noTeamMessagesYet': 'チームメッセージはまだありません。会話を始めましょう。',
      'teamMessageHint': 'チームにリアルタイムでメッセージ',
      'teamMessageSendFailed': 'メッセージ送信に失敗しました: {error}',
      // User listing submissions
      'submitField': 'フィールドを提案する',
      'submitShop': 'ショップを提案する',
      'submitListingHint': '送信後、管理者が審査してから公開されます。',
      'submitListingBtn': '審査のために提出する',
      'submitListingSuccess': '提出しました！管理者が審査します。',
      'submitListingFailed': '提出に失敗しました: {error}',
      'submitListingNameLocationRequired': '名前と場所名は必須です。',
      'submitShopNameAddressRequired': '名前と住所は必須です。',
      'invalidLatLng': '緯度・経度は有効な数値である必要があります。',
      'mySubmissions': '自分の提出一覧',
      'noSubmissionsYet': 'まだ提出はありません。',
      'statusPending': '審査中',
      'statusApproved': '承認済み',
      'statusRejected': '却下',
      'fieldNameLabel': 'フィールド名',
      'shopNameLabel': 'ショップ名',
    },
  };

  String get _languageCode => locale.languageCode;

  String _text(String key) => _localizedValues[_languageCode]?[key] ?? key;

  String t(String key, {Map<String, String> args = const {}}) {
    var value = _text(key);
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  String get appTitle => _text('appTitle');
  String get home => _text('home');
  String get fieldFinder => _text('fieldFinder');
  String get events => _text('events');
  String get meetups => _text('meetups');
  String get settings => _text('settings');
  String get profile => _text('profile');
  String get editProfile => _text('editProfile');
  String get callSign => _text('callSign');
  String get area => _text('area');
  String get teamName => _text('teamName');
  String get loadout => _text('loadout');
  String get instagram => _text('instagram');
  String get facebook => _text('facebook');
  String get youtube => _text('youtube');
  String get save => _text('save');
  String get latestNews => _text('latestNews');
  String get newFields => _text('newFields');
  String get newEvents => _text('newEvents');
  String get newMeetups => _text('newMeetups');
  String get teamPosts => _text('teamPosts');
  String get searchFields => _text('searchFields');
  String get searchByNameLocationType => _text('searchByNameLocationType');
  String get map => _text('map');
  String get list => _text('list');
  String get calendar => _text('calendar');
  String get createMeetup => _text('createMeetup');
  String get title => _text('title');
  String get content => _text('content');
  String get date => _text('date');
  String get time => _text('time');
  String get location => _text('location');
  String get fontSize => _text('fontSize');
  String get theme => _text('theme');
  String get lightMode => _text('lightMode');
  String get darkMode => _text('darkMode');
  String get downloadUpdates => _text('downloadUpdates');
  String get notificationSettings => _text('notificationSettings');
  String get privacySettings => _text('privacySettings');
  String get accountSettings => _text('accountSettings');
  String get language => _text('language');
  String get offlineSync => _text('offlineSync');
  String get fieldContact => _text('fieldContact');
  String get website => _text('website');
  String get socialProfiles => _text('socialProfiles');
  String get contacts => _text('contacts');
  String get messages => _text('messages');
  String get addContact => _text('addContact');
  String get contactRequests => _text('contactRequests');

  // ── Membership ──────────────────────────────────────────────────────────
  String get annualMembership => _text('annualMembership');
  String get annualPlan => _text('annualPlan');
  String get membershipProcess => _text('membershipProcess');
  String get membershipFullName => _text('membershipFullName');
  String get membershipContactEmail => _text('membershipContactEmail');
  String get membershipNotesHint => _text('membershipNotesHint');
  String get membershipSubmitting => _text('membershipSubmitting');
  String get membershipRequestBtn => _text('membershipRequestBtn');
  String get membershipRequestSent => _text('membershipRequestSent');
  String get membershipNameEmailRequired => _text('membershipNameEmailRequired');
  String get membershipStatusNone => _text('membershipStatusNone');
  String get membershipStatusPending => _text('membershipStatusPending');
  String get membershipStatusApproved => _text('membershipStatusApproved');
  String get membershipStatusRejected => _text('membershipStatusRejected');
  String get membershipStatusPaymentRequested => _text('membershipStatusPaymentRequested');
  String get membershipStatusActive => _text('membershipStatusActive');
  String get membershipStatusExpired => _text('membershipStatusExpired');

  // ── Team Map ─────────────────────────────────────────────────────────────
  String get tacticalMap => _text('tacticalMap');
  String get uploadMap => _text('uploadMap');
  String get createTacticalMap => _text('createTacticalMap');
  String get mapTitle => _text('mapTitle');
  String get noTeamMapsYet => _text('noTeamMapsYet');
  String get createFirstMap => _text('createFirstMap');
  String get uploadMapBtn => _text('uploadMapBtn');
  String get mapUploadSuccess => _text('mapUploadSuccess');
  String get routeSaved => _text('routeSaved');
  String get mapModeRespawn => _text('mapModeRespawn');
  String get mapModeTarget => _text('mapModeTarget');
  String get mapModeObjective => _text('mapModeObjective');
  String get mapModeWaypoint => _text('mapModeWaypoint');
  String get mapModeRoute => _text('mapModeRoute');
  String get mapModeClear => _text('mapModeClear');
  String get mapSaveRoute => _text('mapSaveRoute');
  String get teamChat => _text('teamChat');

  // ── Team Chat ─────────────────────────────────────────────────────────────
  String get noTeamMessagesYet => _text('noTeamMessagesYet');
  String get teamMessageHint => _text('teamMessageHint');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any(
        (Locale supported) => supported.languageCode == locale.languageCode,
      );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
